---
title: "homework3"
author: "xubingwei"
date: "2025-10-13"
output: html_document
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

1.  

```{r}
gmp <- read.table("E:/postgraduate/data science/mynotes/data/gmp.dat")
gmp$pop <- round(gmp$gmp/gmp$pcgmp)
gmp <- gmp |> mutate(nlmfit_1 = 6611*pop^(1/8),nlmfit_2 = 6611*pop^0.1,nlmfit_3 = 6611*pop^0.15)
gmp |> ggplot()+geom_point(aes(x = pop ,y = pcgmp))+labs(x="Populations",y="per capita GMP ")+
     scale_x_log10()+
     geom_line(aes(x = pop, y = nlmfit_1), col = 'blue', size = 1.5)+
     geom_line(aes(x = pop, y = nlmfit_2), col = 'red', size = 1.5)+
     geom_line(aes(x = pop, y = nlmfit_3), col = 'green', size = 1.5)
```

2.  

```{r}
mse <- function(params,N=gmp$pop,Y=gmp$pcgmp){
  stopifnot(is.numeric(params),length(params) == 2)
  y0 <- params[1]
  a <- params[2]
  mse_val <- mean((Y - y0 * (N^a))^2)
  return(mse_val)
}
```

3.  minimum指的是在优化后可以取得的mse()函数的最小值，estimate指的是minimum取得最小值时的参数y0和a的取值
    返回值分别为：

```         
1).nlm(mse, c(y0=6611,a=1/8))
$minimum
[1] 61857060

$estimate
[1] 6611.0000000    0.1263177

$gradient
[1] 50.048639 -9.983778

$code
[1] 2

$iterations
[1] 3

2).nlm(mse, c(y0=6611,a=0.1))
$minimum
[1] 61857060

$estimate
[1] 6611.0000003    0.1263177

$gradient
[1]   50.04683 -166.46832

$code
[1] 2

$iterations
[1] 6

3).nlm(mse, c(y0=5000,a=0.15))
$minimum
[1] 62521484

$estimate
[1] 5000.0000000    0.1475913

$gradient
[1] -1028.22522    25.81742

$code
[1] 2

$iterations
[1] 4
```
4.
```{r}
plm <- function(y0,a,N=gmp$pop,Y=gmp$pcgmp){
  res <- nlm(mse,c(y0,a),N = N, Y = Y)
  return(list(y0=res$estimate[1],a=res$estimate[2],mse=res$minimum))
}

result1 <- plm(y0 = 6611, a = 0.15)
cat("从 (6611, 0.15) 开始的结果:\n")
cat("y0 =", result1$y0, "\n")         #y0 = 6611 
cat("a =", result1$a, "\n")           #a = 0.1263182
cat("MSE =", result1$mse, "\n\n")     #MSE = 61857060

result2 <- plm(y0 = 5000, a = 0.10)
cat("从 (5000, 0.10) 开始的结果:\n")
cat("y0 =", result2$y0, "\n")         #y0 = 5000 
cat("a =", result2$a, "\n")           #a = 0.1475913 
cat("MSE =", result2$mse, "\n")       #MSE = 62521484 
```
从y0=6611,a=0.15开始和y0=5000,a=0.10开始参数估计不同，可能因为目标函数有多个不同的局部最小值，优化算法还没有完全收敛。估计值y0=6611,a=0.126有更小的MSE

5.
a.
```{r}
mean(gmp$pcgmp)   #32922.53
n <- nrow(gmp)
sd_pcgmp <- sd(gmp$pcgmp)
se_mean <- sd_pcgmp / sqrt(n)  #481.9195
```
b.
```{r}
mean_exi <- function(i){
  stopifnot(i>0,i<=nrow(gmp))
  return(mean(gmp$pcgmp[-i]))
}
```
c.
```{r}
n <- nrow(gmp)   
jackknifed.means <- numeric(n)
for (i in 1:n) {
  jackknifed.means[i] <- mean_exi(i)
}
```
d.
```{r}
jackknife_variance <- ((n-1)/n) * sum((jackknifed.means - mean(jackknifed.means))^2)
jackknife_se <- sqrt(jackknife_variance)   #481.9195
abs(jackknife_se - se_mean)    #jackknife standard error与(a)计算的standard error 相差1.875833e-12
abs(jackknife_se - se_mean)/se_mean * 100  #相对差异
```
6.
```{r}
n <- nrow(gmp)
 plm.jackknife <- function(y0,a,N=gmp$pop,Y=gmp$pcgmp){
   y0.means <- numeric(n)
   a.means <- numeric(n)
   for (i in 1:n) {
     res = plm(y0,a,N=N[-i],Y=Y[-i])
     y0.means[i] <- res$y0
     a.means[i] <- res$a
   }
   y0.mean <- mean(y0.means)
   a.mean <- mean(a.means)
   y0_se <- sqrt(((n-1)/n) * sum((y0.means - y0.mean)^2))
   a_se <- sqrt(((n-1)/n) * sum((a.means - a.mean)^2))
   #y0_se <- sqrt((((n-1)^2)/n)*var(y0.means))
   #a_se <- sqrt((((n-1)^2)/n)*var(a.means))
   return(list(y0_se=y0_se,a_se=a_se))
 }
```
7.
```{r}
gmp_2013 <- read.table("E:/postgraduate/data science/mynotes/data/gmp-2013.dat")
gmp_2013$pop <- round(gmp_2013$gmp/gmp_2013$pcgmp)
plm(y0=6611,a=0.15,N=gmp_2013$pop,Y=gmp_2013$pcgmp)
plm.jackknife(6611,0.15,N=gmp_2013$pop,Y=gmp_2013$pcgmp)
```
