---
title: "homework2"
author: "xbw"
date: "2025-09-19"
output:
  html_document: default
  word_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(repos = c(CRAN = "https://mirrors.zju.edu.cn/CRAN/" )) # 设置CRAN镜像
```

1.  

    a.  

    ```{r}
    ca_pa <- read.csv("E:/postgraduate/data science/mynotes/data/calif_penn_2011.csv")
    ```

    b.  

    ```{r}
    nrow(ca_pa) #[1] 11275
    ncol(ca_pa) #[1] 34
    ```

    c.统计每一列中元素是缺失值(NA)的数量

    d.  

    ```{r}
    ca_pa_omitna <- na.omit(ca_pa)
    ```

    e.omitted 10576 rows\
    f.(c)和(e)的答案不一致，因为(c)统计的是每一列有多少个元素是na，而(e)删除的是有na元素的行

2.  

    a.  

    ```{r}
    install.packages("tidyverse")
    library(tidyverse)
    # Plot median house prices 与 Built_2005_or_later的关系
    ca_pa_omitna |> ggplot()+aes(x=Built_2005_or_later,y=Median_house_value)+geom_point()+ labs( x = "Built_2005_or_later", y = "Median_house_value")
    ```

    b.  

    ```{r}
    #根据所在州对数据进行区分
    ca_pa_omitna |> ggplot()+aes(x=Built_2005_or_later,y=Median_house_value,color=STATEFP)+geom_point()+ labs( x = "Built_2005_or_later", y = "Median_house_value")
    ```

    c.  

    ```{r}
    ca_pa$vacancy_rate <- ca_pa$Vacant_units/ca_pa$Total_units
    ```

3.  

    a.  

    ```{r}
    min(ca_pa$vacancy_rate,na.rm=TRUE) #0
    max(ca_pa$vacancy_rate,na.rm=TRUE) #1
    mean(ca_pa$vacancy_rate,na.rm=TRUE) #0.08917878
    median(ca_pa$vacancy_rate,na.rm=TRUE) #0.06766326
    ```

    b.  

    ```{r}
    ca_pa |> ggplot()+aes(x=Median_house_value,y=vacancy_rate)+geom_point()+labs(x="Median_house_value",y="vacancy_rate")
    ```

    c.  

    ```{r}
    ca_pa |> ggplot()+aes(x=Median_house_value,y=vacancy_rate)+geom_point()+labs(x="Median_house_value",y="vacancy_rate")+facet_wrap(~STATEFP)
    #宾夕法尼亚州中位房屋价值越高的区域空置率越低，而加利福尼亚州的房屋空置率分布比较均匀
    ```

4.  

    a.  

    ```{r}
    #这段代码要实现将Alameda County，California的median_house_value列成一个vector，并求中间值
    acca <- c() #先创建一个空vector，用于存储行号
     for (tract in 1:nrow(ca_pa)) {#从第一行遍历到末尾
     if (ca_pa$STATEFP[tract] == 6) {
     if (ca_pa$COUNTYFP[tract] == 1) {
     acca <- c(acca, tract) #将STATEFP==6且COUNTYFP==1的行号添加到acca中
     }
     }
     }
     accamhv <- c() #创建空vector，
     for (tract in acca) { #遍历acca
     accamhv <- c(accamhv, ca_pa[tract,10]) #将每一行的第十列即median_house_value添加到accamhv中
     }
     median(accamhv)#求Alameda County，California的median_house_value的中间值
    ```

    b.  

    ```{r}
    median(ca_pa[ca_pa$STATEFP == 6 & ca_pa$COUNTYFP == 1, 10], na.rm = TRUE)
    ```

    c.  

    ```{r}
    #Alameda County average percentages of housing built since 2005 is 2.932778
    mean(ca_pa[ca_pa$STATEFP == 6 & ca_pa$COUNTYFP == 1,"Built_2005_or_later"],na.rm = TRUE)
    # Santa Clara average percentages of housing built since 2005 is 3.160215
    mean(ca_pa[ca_pa$STATEFP == 6 & ca_pa$COUNTYFP == 85,"Built_2005_or_later"],na.rm = TRUE)
    #Allegheny County average percentages of housing built since 2005 is 1.883375
    mean(ca_pa[ca_pa$STATEFP == 42 & ca_pa$COUNTYFP == 3,"Built_2005_or_later"],na.rm = TRUE)
    ```

    d.(i).the whole data

    ```{r}
    # the whole data -0.02052684
    cor(ca_pa$Median_house_value,ca_pa$Built_2005_or_later,use = "complete.obs")

    ```

    (ii). all of California

    ```{r}
    # 0.2339447
     cor(ca_pa[ca_pa$STATEFP == 42,c("Median_house_value","Built_2005_or_later")],use = "complete.obs")
    ```

    (iii). all of Pennsylvania

    ```{r}
    # -0.1160322
    cor(ca_pa[ca_pa$STATEFP == 6,c("Median_house_value","Built_2005_or_later")],use = "complete.obs")
    ```

    (iv). Alameda County

    ```{r}
    #  0.01432789
    cor(ca_pa[ca_pa$STATEFP == 6 & ca_pa$COUNTYFP == 1,c("Median_house_value","Built_2005_or_later")],use = "complete.obs")
    ```

    (v). Santa Clara County

    ```{r}
    # -0.1726203
    cor(ca_pa[ca_pa$STATEFP == 6 & ca_pa$COUNTYFP == 85,c("Median_house_value","Built_2005_or_later")],use = "complete.obs")
    ```

    (vi). Allegheny County

    ```{r}
    # 0.1868602
    cor(ca_pa[ca_pa$STATEFP == 42 & ca_pa$COUNTYFP == 3,c("Median_house_value","Built_2005_or_later")],use = "complete.obs")
    ```

<!-- -->

e.  

```{r}
#先将三个城市的信息提取出来
ca_pa_sub <- ca_pa[ca_pa$STATEFP == 6 & ca_pa$COUNTYFP == 1 |ca_pa$STATEFP == 6 & ca_pa$COUNTYFP == 85 | ca_pa$STATEFP == 42 & ca_pa$COUNTYFP == 3,c("STATEFP","COUNTYFP","Median_house_value","Median_household_income")]
#添加城市列名
ca_pa_sub$County <- ifelse(ca_pa_sub$STATEFP == 6 & ca_pa_sub$COUNTYFP == 1, "Alamed", ifelse(ca_pa_sub$STATEFP == 6 & ca_pa_sub$COUNTYFP == 85, "Santa Clara","Allegheny"))
#画出三个城市的图，用County区分
ca_pa_sub |> ggplot()+aes(x=Median_house_value,y=Median_household_income,color=County,shape = County)+geom_point() + labs(x="Median_house_value",y="Median_household_income",color="County",shape = "County")
```

MB.Ch1.11.

```{r}
#将"female"重复91次，"male"重复92次连接成一个字符串向量，将字符串向量转化为一个因子
gender <- factor(c(rep("female", 91), rep("male", 92)))
 table(gender)#统计gender因子中的每个水平的频次
 
 gender <- factor(gender, levels=c("male", "female")) #将因子gender的水平顺序从默认顺序改为指定的c("male", "female")顺序
 
 gender <- factor(gender, levels=c("Male", "female"))
 #"male"无法匹配"Male"，所以被转为NA
 table(gender, exclude=NULL)
 #exclude = NULL：强制显示所有水平，包括NA的计数，上面92个"male"被转换为了NA，所以显示92个NA
```

MB.Ch1.12.

```{r}
proportion_fun <- function(x,cutoff){
  #统计x中大于cutoff的数量
  above_cutoff <- sum(x>cutoff,na.rm=TRUE)
  #统计x的总数
  total <- sum(!is.na(x))
  return (above_cutoff/total)#返回超过cutoff的比例
}
```

(a).

```{r}
test1 <- 1:100
proportion_fun(test1,25) #0.75
proportion_fun(test1,76) #0.24
```

(b).

```{r}
install.packages("Devore7")
library(Devore7)
data(ex01.36)
escape_times <- ex01.36
dotplot(~escape_times)
proportion_fun(escape_times,420) #0.03846154
```

MB.Ch1.18.

```{r}
install.packages("MASS")
library(MASS)
#将Rabbit根据Treatment、Dose、Animal的优先级排序
rabbit_sorted <- Rabbit[order(Rabbit$Treatment, Rabbit$Dose, Rabbit$Animal), ]
# 使用unstack将Animal展开为列
rabbit_unstack1 <- unstack(rabbit_sorted, BPchange ~ Animal)
# 提取唯一的Treatment和Dose组合
treatment_dose_combos <- unique(rabbit_sorted[, c("Treatment", "Dose")])
# 将treatment_dose_combos 和 rabbit_unstack1 组合成为最终结果
rabbit_unstack <- cbind(treatment_dose_combos,rabbit_unstack1)
print(rabbit_unstack)
```
